server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:9443}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:true}
    key-store: ${SERVER_SSL_KEY_STORE:classpath:keystore.p12}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD:Panda7521ok!}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:PKCS12}
    key-alias: ${SERVER_SSL_KEY_ALIAS:myssl}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: seok7521@gmail.com
    password: xkrfgftiyrhijrix
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: kr.or.kosa.backend.user.domain
  configuration:
    map-underscore-to-camel-case: true

file:
  upload-dir: /home/teamproject/coai/uploads/profile-images

jwt:
  secret: ${JWT_SECRET}